//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chat.Common.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recipient is not using Chat at this time..
        /// </summary>
        public static string CheckMemberTo {
            get {
                return ResourceManager.GetString("CheckMemberTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error on chat server..
        /// </summary>
        public static string CreateVhostChatInternalError {
            get {
                return ResourceManager.GetString("CreateVhostChatInternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to configure chat server..
        /// </summary>
        public static string CreateVhostCouldnt {
            get {
                return ResourceManager.GetString("CreateVhostCouldnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat server is not responding..
        /// </summary>
        public static string CreateVhostGatewayTimeout {
            get {
                return ResourceManager.GetString("CreateVhostGatewayTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat server not found. Check the configuration file..
        /// </summary>
        public static string CreateVhostNotFound {
            get {
                return ResourceManager.GetString("CreateVhostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a message....
        /// </summary>
        public static string EnterMsg {
            get {
                return ResourceManager.GetString("EnterMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your NickName.
        /// </summary>
        public static string EnterNickName {
            get {
                return ResourceManager.GetString("EnterNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only you are using Chat at moment.
        /// </summary>
        public static string OnlyYouChat {
            get {
                return ResourceManager.GetString("OnlyYouChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already a registered user with this NickName.
        /// </summary>
        public static string UserMembersValidate {
            get {
                return ResourceManager.GetString("UserMembersValidate", resourceCulture);
            }
        }
    }
}
