//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chat.Common.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Your Nickname must consist of alphanumeric characters only..
        /// </summary>
        public static string AlphanumericOnly {
            get {
                return ResourceManager.GetString("AlphanumericOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a message....
        /// </summary>
        public static string EnterMsg {
            get {
                return ResourceManager.GetString("EnterMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your nickname:.
        /// </summary>
        public static string EnterYourNickname {
            get {
                return ResourceManager.GetString("EnterYourNickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To send a Private message: Type the Msg Text and assign (=&gt;) to a User - Example: How are you?=&gt;daniel.
        /// </summary>
        public static string ExamplePrivateMsg {
            get {
                return ResourceManager.GetString("ExamplePrivateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To send a Public message: Type only the Message Text - Example: Whats up?.
        /// </summary>
        public static string ExamplePublicMsg {
            get {
                return ResourceManager.GetString("ExamplePublicMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examples for sending messages:.
        /// </summary>
        public static string ExamplesSendMsg {
            get {
                return ResourceManager.GetString("ExamplesSendMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fol all.
        /// </summary>
        public static string ForAll {
            get {
                return ResourceManager.GetString("ForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for you.
        /// </summary>
        public static string ForYou {
            get {
                return ResourceManager.GetString("ForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey... We have new users in Chat:.
        /// </summary>
        public static string NewUsersChat {
            get {
                return ResourceManager.GetString("NewUsersChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What a pity! We don&apos;t have any other users in the chat... Come on... Invite your friends now....
        /// </summary>
        public static string NoUsers {
            get {
                return ResourceManager.GetString("NoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to said.
        /// </summary>
        public static string Said {
            get {
                return ResourceManager.GetString("Said", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Users:.
        /// </summary>
        public static string UsersChat {
            get {
                return ResourceManager.GetString("UsersChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}!.
        /// </summary>
        public static string UserWelcome {
            get {
                return ResourceManager.GetString("UserWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ========&gt;  Welcome to Chat  &lt;========.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
